# Config file for travis-ci.org

language: php

php:
  - "7.0"
  - "5.5"

env:
  - DOKUWIKI=master
  - DOKUWIKI=stable

before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install: sh travis.sh

before_script:
  # Get latest release of PHP_CodeSniffer
  - cd /tmp
  - wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - chmod +x phpcs.phar

  # Get latest release of PHPCompatibility
  - git clone -b master https://github.com/wimg/PHPCompatibility.git /tmp/phpcs-extra/PHPCompatibility
  - cd /tmp/phpcs-extra/PHPCompatibility
  - git checkout $(git describe --tags `git rev-list --tags --max-count=1`) # Checkout latest tag

  - cd $TRAVIS_BUILD_DIR
  - /tmp/phpcs.phar --config-set installed_paths /tmp/phpcs-extra

    # A time zone without daylight saving time for simplified testing (UTC+09:00)
  - echo 'date.timezone = "Asia/Tokyo"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - cd _test && phpunit --stderr --group plugin_icalevents && cd ..
  - cd lib/plugins/icalevents && /tmp/phpcs.phar --standard=PHPCompatibility --runtime-set testVersion 5.5-7.0 --ignore=_test/ . && cd ..
